Added flip video.
sbimochan/zoom-mirror pull request #12
Opened 2020-10-06 09:38 UTC by gareffmz

From issue #10

2020-10-06 09:41 UTC, sbimochan requested changes
commit those suggestions first. Thanks

2020-10-06 09:41 UTC, sbimochan commented on script.js
> +let flipVideo=false;
```suggestion
let mirrorCamera = null;
let flipVideo = false;
```

2020-10-06 09:41 UTC, sbimochan commented on script.js
> +  mirrorCamera= document.querySelector('.mirror-camera');
```suggestion
  mirrorCamera = document.querySelector('.mirror-camera');
```

2020-10-06 09:41 UTC, sbimochan commented on script.js
> +  mirrorCamera.addEventListener('click',checkMirrorCamera)
```suggestion
  mirrorCamera.addEventListener('click', checkMirrorCamera)
```

2020-10-06 09:41 UTC, sbimochan commented on script.js
> +          mirrorCamera.style.display="block";
```suggestion
          mirrorCamera.style.display = "block";
```

2020-10-06 09:41 UTC, sbimochan commented on script.js
> +}
```suggestion
}

```

2020-10-06 09:41 UTC, sbimochan commented on main.css
>  }
```suggestion
}

```

2020-10-06 09:41 UTC, sbimochan commented on main.css
> +}
```suggestion
}

```

2020-10-06 09:43 UTC, sbimochan commented
Make default flipped. and on clicking that flip button,let it be as now.

2020-10-06 09:45 UTC, sbimochan commented
Change that button to rotate icon. Add some box-shadow so it looks more like a button. place it below video-player on bottom right. Or any other better UI is welcome.

2020-10-06 09:47 UTC, sbimochan commented on index.html
> +      <div class="mirror-camera">Flip camera</div>
It should be <button>

2020-10-06 09:48 UTC, sbimochan commented on script.js
> +  }else{
```suggestion
  }else {
```

2020-10-06 12:59 UTC, gareffmz reviewed
I made some changes, to add the suggestions. #12

2020-10-07 05:30 UTC, sbimochan commented
Nice.

2020-10-07 05:30 UTC, merged